facebookresearch/shumai

.gitignore
Seems that the compiled package under macOS is .dylib suffixed.
=> Add dylib to .gitignore

test/mean.test.ts, test/tile.test.ts, test/transpose.test.ts
Suspect the newly added failing tests are a result of the current default to column major (whereas TFJS API defaults to Row Major for Tensor Operations). Per conversation with @bwasti, I'd suggest we imitate TFJS in defaulting to Row Major to enable developer's familiar with Tensorflow.js to explore the API/migrate their codebase.
=> Add Tests for Tile & Mean

examples/train.js, src/cpp/flashlight_binding.cc, src/ffi/ffi_flashlight.ts, src/ffi/ffi_tensor.ts, src/tensor/tensor.ts
Thanks Jacob for recommending this!
By exposing eval, we can control when the JIT (and future JITs) executes.
In train.js, before eval:
After eval:
=> Add `eval()` semantics to JS, for performance

scripts/gen_binding.py, shumai/io/network.ts, shumai/tensor/tensor.ts, shumai/tensor/tensor_interface.ts, shumai/tensor/tensor_ops_gen.ts, shumai/tensor/tensor_ops_interface_gen.ts, shumai/tensor/tensor_ops_shim_gen.ts, shumai/util/index.ts, shumai/util/iterators.ts, shumai/util/types.ts, test/io.test.ts, test/lessThan.test.ts, test/utils.ts, tsconfig.json
Should provide more accurate runtime typings for newly added `io` functionality; fixed some ESLint Errors in the new code, added `lessThan` tests while cleaning up `io` tests  as we need to track down that float underflow issue.
=> Update io types (clean up tests/examples); add lessThan tests

test/all.test.ts, test/argmax.test.ts, test/argmin.test.ts, test/cos.test.ts, test/erf.test.ts, test/flip.test.ts, test/greaterThan.test.ts, test/greaterThanEqual.test.ts, test/isinf.test.ts, test/isnan.test.ts, test/lessThan.test.ts, test/lessThanEqual.test.ts, test/matmul.test.ts, test/mean.test.ts, test/negative.test.ts, test/sigmoid.test.ts, test/sign.test.ts, test/sin.test.ts, test/sum.test.ts, test/tanh.test.ts, test/tile.test.ts, test/transpose.test.ts, test/utils.ts, tsconfig.json
Now that we've fixed the bug in `buffer`, wanted to get the unit tests for greaterThan, greaterThanEqual, & lessThanEqual added.
=> Unit tests for greaterThan, greaterThanEqual, lessThanEqual, & matmul

test/any.test.ts, test/cumsum.test.ts, test/flip.test.ts, test/log1p.test.ts, test/logicalAnd.test.ts, test/logicalNot.test.ts, test/logicalOr.test.ts, test/mean.test.ts, test/sqrt.test.ts, test/transpose.test.ts, test/where.test.ts
Added unit tests for the following operations: `any`, `cumsum`, `log1p`, `logicalAnd`, `logicalNot`, `logicalOr`, `sqrt`, and `where`.
Note: All tests for `where` are failing with a C++ exception, so I've commented the tests out until we've identified the source of the issue/resolved it (thus ensuring the test run isn't cut short by the C++ exception).
=> Added additional unit tests for Ops

shumai/tensor/register_gradients.ts
I think this will help us with type safety when working with `grads`. I'm inferring the types from usage, so it's possible I've missed or mistyped something.
=> add type def for Grads; type fns in `register_gradients.ts`

shumai/io/network.ts
Previously, the JSON returned by `statistics` endpoint destructured the `statistics` property, but the returned JSON is much cleaner if it's structured as this PR proposes. Here's what the resulting JSON looks like with the changes:
=> fix returned JSON structure for `statistics` endpoint

shumai/cpp/flashlight_binding.cc, shumai/ffi/ffi_tensor.ts, shumai/tensor/tensor.ts, test/conv.test.ts, test/dtype.test.ts
Begin implementing functionality to allow control of type underlying tensor data.
In testing, tensor class method `asType` (and similar variations):
```ts
asType(dtype: dtype) {
fl._astype.native(this.ptr, dtype)
}
``` 
were failing to update the type accordingly in the following test:
```ts
const t = sm.tensor(new Float32Array([1, 2, 3]))
t.asType(sm.dtype.Float64)
console.log(t.dType === sm.dtype.Float64, t.dType, sm.dtype.Float64)
```
Outputs:
`false, 1, 2`
As such, I've temporarily removed the `asType` tensor class method pending feedback; if it requires more involved changes to the Tensor class, it might be better to submit as a separate PR as this one is getting a bit crowded.
=> Add Native Fns to Access `fl::dtype` Enum + `_astype`

package.json, scripts/gen_binding.py, shumai/cpp/binding_gen.inl, test/where.test.ts
Updated dependencies (namely ESLint/related Typescript reps); additionally, spent time debugging the failing `where` tests, which led me to identify that Flashlight expects parameter `cond` to have `dtype::b8`; accordingly, updated `gen_binding.py` so that the generated typescript `where` methods both check if `cond.dtype === dtype.BoolInt8`, calling `cond = cond.astype(dtype.BoolInt8)` to convert if the type is inaccurate.
=> update `gen_binding.py` so native fn `_where` casts param `cond` to `fl::dtype::b8`

shumai/ffi/ffi_flashlight.ts, shumai/tensor/tensor.ts
This should simplify installation by allowing folks to install various versions of the native bindings (with fallbacks automatically used)
=> Fallback to CPU versions automatically

test/utils.ts
Add `expectThrows` test function that can be used to test a. that the function passed in as a param throws and b. optionally pass in params to validate that it's throwing the type of error you expect.
Given that whether we want to make use of this on currently commented out tests (not yet fully implemented/ArrayFire not supporting >4 Dims) is a matter of preference, I haven't called the new `expectThrows` fn in any of the unit tests, but here's a snippet demonstrating how to use:
```ts
it('simple', () => {
expectThrows(() => {
const x = sm.full([1, 1, 4, 4], 1)
const w = sm.full([1, 1, 3, 3], 1)
const y = sm.conv2d(x, w)
expect(isShape(y, [1, 1, 2, 2])).toBe(true)
expectArraysClose(y.toFloat32Array(), sm.full([2, 2], 9).toFloat32Array())
})
})
```
=> add `expectThrows` test util

scripts/gen_binding.py, shumai/cpp/binding_gen.inl, shumai/cpp/flashlight_binding.cc
Wrap all remaining native functions that return a pointer in a Try/Catch and call `HANDLE_EXCEPTION` accordingly.
=> `HANDLE_EXCEPTION` for remaining native Fns returning pointer

shumai/optim/sgd.ts
Most use cases won't see any perf benefits, but in general we should always avoid having to do hash lookups when all we're doing is processing all entries.
=> Optimize SGD

docs.md
In part made this PR to make sure the intention of the optimizer was to wipe out the gradients. I get why it was done, but I could argue `backward` could have been responsible for the reset. The way it is now is likely most performant since unreferenced gradients can be freed.
=> Clarify usage of gradients before/after optimizer

scripts/gen_all_binding.sh
Some systems might not have a `python` executable, or it might point to Python 2 instead. For better compatibility, try to use `python3` first, then fall back to `python` if that is not found.
`type -P` searches the system PATH and returns the path to the executable if it is found
`${VAR:-string}` returns `string` if `VAR` is unset.
=> Try alternate python command in gen_all_binding.sh

scripts/gen_binding.py, shumai/cpp/binding_gen.inl, shumai/cpp/flashlight_binding.cc, shumai/ffi/ffi_bind_utils.ts, shumai/ffi/ffi_tensor_ops_gen.ts, shumai/optim/sgd.ts, shumai/tensor/register_gradients.ts, shumai/tensor/tensor.ts, shumai/tensor/tensor_ops_gen.ts, shumai/tensor/tensor_ops_shim_gen.ts, test/concatenate.test.ts, test/utils.ts
For each TensorVector, a Typescript `Array<Tensor>` is converted to a `BigInt64Array` containing pointers to `Tensor`s. This is passed to the FFI as `tensors_ptr` and `tensors_len` which have types `FFIType.ptr` and `FFIType.i64`. In C++, we cast each `uint64_t` in the array to `fl::Tensor*` and dereference it to obtain `std::vector<fl::Tensor>`, which is the type Flashlight expects.
TensorVector is unfolded into individual Tensors before being passed to gradient calculations. As a consequence of this, in general each function can only take at most one TensorVector parameter; if there were multiple TensorVector parameters, the gradient function would be unable to distinguish which TensorVector a given Tensor came from (without some horrible hacks). The alternative would have been to pass …
=> Implemented TensorVector bindings and `sm.concatenate`

shumai/tensor/register_gradients.ts, shumai/tensor/tensor.ts, test/concatenate.test.ts, test/mean.test.ts, test/sum.test.ts
Previously, these gradient functions assumed that the forward function was applied over all axes, and simply tiled the `grad_in` to the same shape as the forward input Tensor. This breaks when the forward function was applied over only a subset of axes, whereupon `grad_in` would not be a scalar and would have the wrong shape when tiled.
This fix was needed in order for the gradients of Transformer-related modules (#78) to behave correctly. This also fixes #74.
Changed `traverse_gradients` and `async_traverse_gradients` to throw an error when `tensor.backward()` is invoked on a non-scalar Tensor. This matches the behaviour in PyTorch. Fixed the gradient and tests of `sm.concatenate` to correctly reflect this behaviour.
=> Fixed gradients of mean and sum

scripts/gen_binding.py, shumai/tensor/tensor.ts, shumai/tensor/tensor_ops_gen.ts, shumai/tensor/tensor_ops_shim_gen.ts
Were a good number of instances where we were still passing `FFIType` to `arrayArg` as a parameter that I have fixed; additionally, you can't compare `x === NaN` in javascript ([weird lang quirk](https://www.loginradius.com/blog/engineering/checking-for-nan-in-javascript/)), so fixed that as well.
=> remove FFIType when calling `arrayArg` and remove import

shumai/tensor/register_gradients.ts, test/basic_ops.test.ts, test/transpose.test.ts
Added gradient functions for `sm.transpose` and `sm.reshape`, along with tests.
=> Gradient for transpose and reshape

CONTRIBUTING.md
Per #82, added info regarding minimum required version of `clang-format` (seems to be required `clang-format` >= `v14.0.0`) to the instructions for new contributors to make getting setup a bit easier.
=> Add Min. `clang-format` Version to `CONTRIBUTING.md`

shumai/module/index.ts, shumai/module/transformer.ts, shumai/tensor/register_gradients.ts, shumai/tensor/tensor.ts, test/transformer.test.ts
Added modules for scaled dot-product attention and multi-head attention, to be used as components of a Transformer.
Added a method, `T()`, to Tensor to perform simple transposition of the last two axes only of a Tensor. This operation is used in several places in a Transformer, as well as in the updated gradient function for `matmul` (the previous version of this gradient function only supported 2D Tensors).
=> Transformer multi-head attention

examples/distributed/data.ts, examples/distributed/differentiate_through_remote_model.ts, examples/python_comparison/serde.ts, shumai/ffi/ffi_bind_utils.ts, shumai/io/network.ts, shumai/module/module.ts, shumai/optim/sgd.ts, shumai/tensor/register_gradients.ts, shumai/tensor/tensor.ts, shumai/util/async.ts, test/concatenate.test.ts
Major type cleanup; believe we went from ~24 ESLint warnings to 2 ESLint warnings after this change (the latter 2 warnings are pending further refinement on network API as we'll be able to replace `any` with a more specific type at that point).
=> Clean Up Types/Fix Transpositional Errors in `register_gradients.ts`

shumai/cpp/flashlight_binding.cc
See title -- including `AutogradExtensionBackends.h` errors out because some of the installed headers it depends on aren't public. Fix this upstream in FL but not installing the header.
Don't dispatch explicitly this way and instead call the detail API call.
=> Don't manually dispatch to conv2dBackwardData

shumai/cpp/flashlight_binding.cc, shumai/ffi/ffi_tensor.ts, shumai/tensor/tensor.ts
Update `valueOf` to automatically handle returning the correct type for JS runtime using switch case on `dtype`. Add native code to handle scalar values. Fixes #86
=> fix `valueOf` to automatically return based on dtype

scripts/gen_binding.py, shumai/tensor/tensor_ops_gen.ts, shumai/tensor/tensor_ops_interface_gen.ts
Also applied `valid_js` to the interface ops as well.
Previously the interface methods generated were slightly out of sync with the actual shim methods (discovered this why trying to use `tensor.var()`).
=> Added aliases to tensor_ops_interface_gen to match tensor_ops_gen

shumai/tensor/register_gradients.ts, test/sqrt.test.ts
Gradient for Y = sqrt(X): dY/dX = 1 / (2 * sqrt(X))
Gradient for Y = var(X) = (X - mean)^2 / n: dY/dX = (2 / n) * (X - mean)
n is the number of elements
Modified the type of grad.in to also allow `boolean` and `BigInt64Array`
=> Gradient for sqrt and variance

shumai/module/index.ts, shumai/module/linear.ts, shumai/module/lstm.ts, shumai/module/norm.ts, shumai/tensor/register_gradients.ts, shumai/tensor/tensor.ts, test/linear.test.ts
I don't think there is any reason that these modules shouldn't work on single vectors in principle. In practice this mostly makes it easier to use them in test cases.
This should broadcast the single dimension of `bias` to all other axes.
Fixed the gradient of `matmul()` and fixed `T()` to work with 0D and 1D Tensors.
=> Get `matmul` gradient, `T`, Linear and LSTM working with 1D tensors

test/utils.ts
Made changes to `isClose` test helper so that it shouldn't bug out when testing 2 `BigInt` values against a non-integer `error` tolerance value. 
If error is not an integer, scale up `error *= 10` (while simultaneously scaling expected/actual @ same rate) until `error` is an integer and test won't fail.
=> fix `isClose` test helper for `BigInt` comparisons

shumai/tensor/tensor.ts, test/utils.ts
Moved the `console.warn` regarding no native JS Float16Array  into Tensor class method `toFloat16Array` so the warning will be logged if calling `valueOf` or directly calling `toFloat16Array`.
Additionally, updated the conditional used in the `while` loop in `isClose` per feedback from @yushiyangk!
=> tweak `while` cond. in `isClose` per feedback/Move Float16Array Warning

.circleci/config.yml
Fixes sporadic issues in ArrayFire 3.8.1 on macOS when installed via Homebrew. The CI Homebrew cache is fixed/won't update (to save CI time), but fixing the version should force a query against the remote package version cache.
=> Fix ArrayFire 3.8.2. in CI

shumai/cpp/flashlight_binding.cc, shumai/ffi/ffi_tensor.ts, shumai/tensor/tensor.ts, test/dispose.test.ts
Bun appears to run GC twice; if you uncomment the logged output in `destroyTensor` (only called @ Garbage Collection), the output is logged multiple times per pointer).
This causes the test to segfault as first GC, bun finds the pointer in `alreadyDestroyed` & removes the pointer from the set. 2nd Garbage Collection, `destroyTensor` fails to locate the pointer in `alreadyDestroyed` (as it was just cleared @ the prev Garbage Collection run).
It seems like there might be a bug in Bun, working on a [repro](https://github.com/cryptodeal/GC_Bug) to file an issue w Bun as this is likely blocking.
Once we resolve the above, this will partially implement #50 (still want to implement some equivalent to TFJS `tidy` in a separate PR).
=> Implement `dispose`

shumai/module/transformer.ts, test/transformer.test.ts
$$ \mathrm{PE}_{i, 2z} = \sin \left( \frac{i}{10000^{2z/d}} \right) $$
$$ \mathrm{PE}_{i, 2z + 1} = \cos \left( \frac{i}{10000^{2z/d}} \right) $$
where $i$ is the sequence position, $2z$ and $2z+1$ are the dimensions of the input embedding, and $d$ is the dimensionality of the input embedding.
The multiplicative factors $\frac{1}{10000^{2z/d}}$ are precomputed during object creation as they are constant for all $i$.
The full PE is initially precomputed for all $i$ up to 256 (configurable). This is then extended and stored if the module is called with a sequence length larger than the initial value.
Returns a 2D tensor matching the last two dimensions of the input tensor to TransformerEncoder.
Simple 2-layer fully connected neural network with relu activation. This is kept as a private …
=> Transformer encoder

examples/remote_runner_example.ts, shumai/network/model.ts, shumai/network/runner.ts
Use Bun's `ServeOptions` type since that's exported from `bun-types` as of now; additionally, destructure `bundled` in `runner.ts` to fix a TypeError.
=> cleanup network & runner

scripts/gen_binding.py, shumai/cpp/binding_gen.inl, test/triu_tril.test.ts
As discussed on discord, `sm.tril` should call `fl::triu`  instead of `fl::tril` when using row major, and vice versa.
=> Fixed `triu` and `tril` being swapped

shumai/network/model.ts, shumai/tensor/register_gradients.ts, shumai/tensor/tensor.ts, shumai/tensor/tensor_ops.ts
Clear naming is subjective, but tried to be more explicit.
=> More explicit gradient state interface

shumai/module/norm.ts
When we `resetParameters`, the new tensors should also require grads.
=> LayerNorm should always requireGrad on beta, gamma

examples/client.ts, examples/distributed/differentiate_through_remote_model.ts, examples/distributed/identity_server.ts, examples/distributed/model_a.ts, examples/distributed/model_b.ts, package.json, shumai/network/model.ts, tsconfig.json, tsconfig.typedoc.json
`typedoc` allows passing a cli arg that specifies that path of the `tsconfig.json` file to be used; accordingly, we now leverage this to specify that `typedoc` should use `tsconfig.typedoc.json`; this allows us to `exclude: ['examples/**/*']` in `tsconfig.typedoc.json` whereas we include in `tsconfig.json`!
=> add separate tsconfig for typedoc gen

shumai/optim/adam.ts, shumai/optim/sgd.ts, shumai/tensor/tensor.ts, shumai/tensor/tensor_ops.ts, shumai/util/memory.ts
Partially addresses https://github.com/facebookresearch/shumai/issues/125 but this PR mainly addresses memory leaks during back-prop optimization. Hopefully supporting nested tidy's will encourage internal usage without worry of side-effects from calling apps also using `tidy`.
=> Tidy optimizers, nested tidy support, and no forced GCs

shumai/tensor/register_gradients.ts, shumai/tensor/tensor_ops.ts, test/gradient.test.ts, test/softmax.test.ts
Modified the softmax function to be numerically stable with large exponents. Method taken from [here](https://cs231n.github.io/linear-classify/#softmax-classifier).
I am fairly new to autodiff gradient functions, so my implementation of `amax` may be way off the mark (it certainly _looks_ wrong).
I originally wrote the below code based on the min/max gradient functions that already exist, but it would not converge my test model (where the current implementation does).
```ts
const mask = ctx.forward_inputs[0]
.eq(ctx.forward_output)
.astype(ctx.backward_input.dtype);
return ctx.backward_input.mul(mask)
```
=> Making softmax numerically stable

test/gradient.test.ts
I guess there was still a (small) probability `randn + 1` could still be up against 0.
=> Fix log gradient test

shumai/loss/index.ts, test/loss.test.ts
This PR adds some common loss functions to compliment the existing `mse` loss.
I have chosen to implement the loss functions as creator functions `(options) => (y, yhat) => number` to accommodate adding configuration options to these functions in the future.
For example, torch's [`cross_entropy`](https://pytorch.org/docs/stable/generated/torch.nn.functional.cross_entropy.html) function accepts `reduction: "mean" | "sum" | "none"` as a configuration option.
This could then be available to users as such:
```ts
// model.ts
export const loss = sm.loss.crossEntropy({ reduction: "mean" });
```
But if you have other plans I am more than happy to remove the pattern.
=> Add mae, cross-entropy, and binary cross-entropy loss fns

shumai/stats/stats.ts
Useful for flushing prior to process or thread exit.
=> stats.flush support

shumai/stats/stats.ts
This prevents stats from recursively spamming loggers while prior flushes are pending.
=> Resolve race condition with stats

.circleci/config.yml
See title. [Context here](https://discuss.circleci.com/t/cuda-11-8-gpu-cuda-image-any-plans/47240). We can use gcc 9 standard because CUDA 11's nvcc supports it
Test plan: CI
=> Use new CircleCI CUDA images, downgrade to medium GPU instance
