facebookresearch/shumai

.github/workflows/build.yml

We've got a self-hosted M1 runner now, so this can be added :)

Add M1 to build

---

.github/workflows/build.yml

Added until we have better Flashlight multibackend support that we can bind and use directly.

[pkg] Add temporary Linux CPU native lib package

---

scripts/gen_binding.py
src/ffi/ffi_bind_utils.ts
src/tensor/tensor_ops_gen.ts
src/tensor/tensor_ops_interface_gen.ts
src/tensor/tensor_ops_shim_gen.ts
tsconfig.json

Cleaned up PR, no code changes to the FFI tweaks. Will submit eval tuner as a separate PR once I've done further testing against benchmarks.

Clean up FFI Tweaks PR

---

scripts/gen_binding.py
shumai.ts
src/cpp/binding_gen.inl
src/tensor/tensor.ts

MM had bad layout handling (dynamically supporting both row and col major is hard lol)

Improve layout handling

---

shumai.ts
src/util/iterators.ts
test/util.test.ts

A pythonic range constructor:
```javascript
for (let i of sm.util.range(100)) {
// blah
}
```
A shuffle utility:
```javascript
for (let i of sm.util.shuffle(array)) {
// blah
}
```

Add some iterator utilities to shumai

---

examples/distributed/model.ts
examples/distributed/model_a.ts
examples/distributed/model_b.ts
examples/serve.ts
shumai/io/network.ts
shumai/loss/index.ts
shumai/module/linear.ts
shumai/module/lstm.ts
shumai/module/module.ts
shumai/optim/index.ts
shumai/tensor/tensor.ts
shumai/tensor/tensor_interface.ts
shumai/util/iterators.ts

A few areas where further refinement is required (namely specifying types for route functions & generic for statistics). I've left comments in the code where I intend to go back and do some additional work tomorrow (but if y'all are good with the changes as is, we can merge this and submit a separate PR for those additional changes).

io type fixes; pending a few further updates

---

shumai/cpp/flashlight_binding.cc
tsconfig.json

Additionally, slight tweak to path in `tsconfig.json` @ exclude property so that the `@shumai/shumai` path alias works in `examples/*.ts`

fix float underflow in native buffer fn

---

scripts/gen_binding.py
shumai/cpp/binding_gen.inl
shumai/cpp/flashlight_binding.cc
shumai/ffi/ffi_tensor_ops_gen.ts
shumai/tensor/tensor_ops_gen.ts
shumai/tensor/tensor_ops_shim_gen.ts
test/cumsum.test.ts

Really appreciate the help from @bwasti in getting this fix working as I haven't really worked with C++ previously, and this has been an incredibly useful in helping me pick it up so that I can, hopefully, start contributing a bit more to this side of the codebase as needed. 
Results from tests run on M1 MacBook Pro Locally

fix axisArgs, allowing dynamic row-major/col-major

---

shumai/io/network.ts

Title sums it up ^^
Very minor tweaks to get `bytes_used` data per model charted in [Distributed Training Dashboard (WIP)](https://github.com/cryptodeal/shumai-dataviz) and a few minor type changes.

add  `bytes_used` to default stats; tweak types in `network.ts`

---

examples/distributed/data.ts
package.json
shumai/io/network.ts
shumai/tensor/stats.ts
shumai/tensor/tensor.ts

Title ^^ Also update utility dep versions (ESLint, Prettier, etc.) and minor type changes to clean up Network types a bit further.

Add `op_stats` as Default Network Statistic

---

.gitignore
.vscode/settings.json
shumai/cpp/flashlight_binding.cc
shumai/ffi/ffi_tensor.ts
shumai/tensor/tensor.ts
test/dtype.test.ts

Title pretty much sums it up; also added more unit tests for the `astype` function in addition to writing unit tests calling `Tensor` constructor with each of the JS `TypedArray` implementations.
(also updated `.gitignore` to exclude `.vscode/` directory config files)

Create Tensor w `dtype` matching instance of `TypedArray` passed to constructor

---

shumai/cpp/flashlight_binding.cc
shumai/ffi/ffi_tensor.ts
shumai/tensor/tensor.ts
test/conv2dBackward.test.ts

Add `conv2dBackwardData` to `flashlight_binding.cc` & update `ffi_tensor.ts` accordingly; remaining changes are purely enforcing formatting standards w `bun format`.

expose native Fn `conv2dBackwardData` in `flashlight_binding.cc`

---

shumai/cpp/flashlight_binding.cc

tweak `HANDLE_EXCEPTION` formatting to mirror Bun

---

README.md

Works great, even if native isn't supported yet. Also aligns with Bun's WSL2 requirement.

Windows support

---

package.json
shumai/optim/sgd.ts
shumai/tensor/tensor.ts

Update dependencies, mostly to get `bun-types` to match latest release of Bun.sh. Also ran `bun format` to clean up formatting.

Update Dependencies (Mainly `bun-types` to `0.2.0`)

---

shumai/tensor/index.ts
shumai/tensor/tensor.ts
shumai/tensor/tensor_ops.ts
test/softmax.test.ts

Added a softmax function. Added a new file to contain `sm.*` operations that are not automatically generated.

Added `softmax` with tests

---

shumai/module/index.ts
shumai/module/norm.ts
test/LayerNorm.test.ts

The argument `dims` gives the shape of the final axes over which LayerNorm should be applied.
LayerNorm(X) = (X - mean) / sqrt(variance + eps) * gamma + beta
for learnable parameters gamma and beta.
Used in Transformer.

Added LayerNorm

---

shumai/module/sequential.ts
shumai/module/transformer.ts
shumai/tensor/register_gradients.ts
test/transformer.test.ts

TransformerDecoderLayer and TransformerDecoder are analogous to those of the encoder in #97

Transformer decoder

---

shumai/module/transformer.ts

Main issue is changing 'encoder' to 'decoder' in TransformerDecoder

Fix transformer docs

---

shumai/tensor/tensor_ops.ts

Didn't bother with tests since activation tests need refactored anyway

Gelu activation support

---

README.md
shumai/tensor/tensor.ts
shumai/util/memory.ts

Resolves https://github.com/facebookresearch/shumai/issues/125

Memory management

---

scripts/gen_binding.py
shumai/tensor/index.ts
shumai/tensor/op_to_flops.ts
shumai/tensor/stats.ts
shumai/tensor/tensor_ops_gen.ts
shumai/tensor/tensor_ops_shim_gen.ts
test/op_to_flops.test.ts

Two objectives with this PR:
* Provide an approximation for operation statistics
* Expose an accumulation helper for surfacing aggregated stats over across time and tensors

Stats summary & operations support

---

shumai/tensor/tensor.ts
shumai/util/memory.ts
test/dispose.test.ts

https://github.com/facebookresearch/shumai/issues/143

Safe dispose, nested tidy, and tidyExclude
